convert all workflows to re-usable

diff --git a/.github/workflows/dev-build-tests_v2.yml b/.github/workflows/dev-build-tests_v2.yml
--- a/.github/workflows/dev-build-tests_v2.yml
+++ b/.github/workflows/dev-build-tests_v2.yml
@@ -1,19 +1,10 @@
-name: try-runtime
+name: yarn test dev
 
 # Controls when the action will run.
 on:
  # Triggers the workflow on push or pull request events but only for the master branch
-  pull_request:
-    branches:
-      - master
-    types:
-      - opened
-      - reopened
-      - synchronize   #commit(s) pushed to the pull request
-      - ready_for_review
+  workflow_call:
 
-  # Allows you to run this workflow manually from the Actions tab
-  workflow_dispatch:
 
 #Define Workflow variables
 env:
@@ -25,10 +16,12 @@ concurrency:
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  try-runtime:
+  
+  dev_build_int_tests:
     # The type of runner that the job will run on
-    runs-on: self-hosted-ci
-    
+    runs-on: [self-hosted-ci,medium]
+    timeout-minutes: 1380
+
     name: ${{ matrix.network }}
 
     continue-on-error: true         #Do not stop testing of matrix runs failed.  As it decided during PR review - it required 50/50& Let's check it with false.
@@ -36,15 +29,12 @@ jobs:
     strategy:
       matrix:
         include:
-          - network: opal
-            features: try-runtime,opal-runtime
-            replica_from_address: wss://eu-ws-opal.unique.network:443
-          - network: quartz
-            features: try-runtime,quartz-runtime
-            replica_from_address: wss://eu-ws-quartz.unique.network:443
-          - network: unique
-            features: try-runtime,unique-runtime
-            replica_from_address: wss://eu-ws.unique.network:443
+          - network: "opal"
+            features: "opal-runtime"
+          - network: "quartz"
+            features: "quartz-runtime"
+          - network: "unique"
+            features: "unique-runtime"
 
     steps:
       - name: Skip if pull request is in Draft
@@ -65,7 +55,6 @@ jobs:
         if: github.event.pull_request.draft == true
         run: exit 1
 
-
       - name: Clean Workspace
         uses: AutoModality/action-clean@v1.1.0
 
@@ -80,29 +69,48 @@ jobs:
       - name: Generate ENV related extend file for docker-compose
         uses: cuchi/jinja2-action@v1.2.0
         with:
-          template: .docker/docker-compose.try-runtime.j2
-          output_file: .docker/docker-compose.try-runtime.${{ matrix.network }}.yml
+          template: .docker/docker-compose.tmp-dev.j2
+          output_file: .docker/docker-compose.${{ matrix.network }}.yml
           variables: |
             RUST_TOOLCHAIN=${{ env.RUST_TOOLCHAIN }}
             FEATURE=${{ matrix.features }}
-            REPLICA_FROM=${{ matrix.replica_from_address }}
+    
 
       - name: Show build configuration
-        run: cat .docker/docker-compose.try-runtime.${{ matrix.network }}.yml
+        run: cat .docker/docker-compose.${{ matrix.network }}.yml
 
       - name: Build the stack
-        run: docker-compose -f ".docker/docker-compose-try-runtime.yml" -f ".docker/docker-compose.try-runtime.${{ matrix.network }}.yml" up --build  --force-recreate --timeout 300 --remove-orphans --exit-code-from try-runtime
- 
-      - name: Collect Docker Logs
-        if: success() || failure()
-        uses: jwalton/gh-docker-logs@v2.2.0
-        with:
-          dest: './try-runtime-logs.${{ matrix.network }}'
-          images: 'try-runtime' 
+        run: docker-compose -f ".docker/docker-compose-dev.yaml" -f ".docker/docker-compose.${{ matrix.network }}.yml" up -d --build --remove-orphans
 
-      - name: Show docker logs
-        run: cat './try-runtime-logs.${{ matrix.network }}/try-runtime.log'
+      - uses: actions/setup-node@v3
+        with:
+          node-version: 16
+
+      - name: Run tests
+        run: |
+          cd tests
+          yarn install
+          yarn add mochawesome
+          echo "Ready to start tests"
+          node scripts/readyness.js
+          NOW=$(date +%s) && yarn test --reporter mochawesome --reporter-options reportFilename=test-${NOW}
+        env:
+          RPC_URL: http://127.0.0.1:9933/
+
+      - name: Test Report
+        uses: phoenix-actions/test-reporting@v8
+        id: test-report
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: int test results - ${{ matrix.network }}            # Name of the check run which will be created
+          path: tests/mochawesome-report/test-*.json    # Path to test results
+          reporter: mochawesome-json
+          fail-on-error: 'false'
+
+      - name: Read output variables
+        run: |
+          echo "url is ${{ steps.test-report.outputs.runHtmlUrl }}"
 
       - name: Stop running containers
         if: always()                   # run this step always
-        run: docker-compose -f ".docker/docker-compose-try-runtime.yml" -f ".docker/docker-compose.try-runtime.${{ matrix.network }}.yml" down
+        run: docker-compose -f ".docker/docker-compose-dev.yaml" -f ".docker/docker-compose.${{ matrix.network }}.yml" down
