Added else condition

diff --git a/.github/workflows/forkless-update-nodata.yml b/.github/workflows/forkless-update-nodata.yml
--- a/.github/workflows/forkless-update-nodata.yml
+++ b/.github/workflows/forkless-update-nodata.yml
@@ -150,6 +150,10 @@ jobs:
                         echo "🛸 PARACHAINS' RUNTIME UPGRADE TESTING COMPLETE 🛸"
                         return 0
                         exit 1
+                    else 
+                        echo "🛸 PARACHAINS' RUNTIME UPGRADE TESTING COMPLETE 🛸 - Not found in logs output."
+                        return 1
+                        exit 1
                     fi
                 else
                     echo "Container node-parachain not RUNNING"
