separate forkless build and tests

diff --git a/.github/workflows/forkless-update-nodata.yml b/.github/workflows/forkless-update-nodata.yml
--- a/.github/workflows/forkless-update-nodata.yml
+++ b/.github/workflows/forkless-update-nodata.yml
@@ -40,7 +40,7 @@ jobs:
             network {sapphire}, wasm_name {quartz}, mainnet_branch {${{ env.SAPPHIRE_MAINNET_BRANCH }}}, relay_branch {${{ env.UNIQUEEAST_MAINNET_BRANCH }}}
 
 
-  forkless-update-nodata:
+  forkless-nodata-build:
     needs: execution-marix
     # The type of runner that the job will run on
     runs-on: [self-hosted-ci,large]
@@ -67,59 +67,156 @@ jobs:
       - name: Read .env file
         uses: xom9ikk/dotenv@v2
 
-      - name: Generate ENV related extend file for docker-compose
+      # Prepare SHA  
+      - name: Prepare SHA
+        uses: ./.github/actions/prepare
+
+      - name: Log in to Docker Hub
+        uses: docker/login-action@v2.0.0
+        with:
+          username: ${{ secrets.CORE_DOCKERHUB_USERNAME }}
+          password: ${{ secrets.CORE_DOCKERHUB_TOKEN }}
+
+      # Build main image for FORKLESS-UPDATE-NODATA
+      - name: Generate ENV related extend Dockerfile file
         uses: cuchi/jinja2-action@v1.2.0
         with:
-          template: .docker/docker-compose.tmp-forkless-nodata.j2
-          output_file: .docker/docker-compose.${{ matrix.network }}.yml
+          template: .docker/Dockerfile-parachain-upgrade.j2
+          output_file: .docker/Dockerfile-parachain-upgrade.${{ matrix.network }}.yml
           variables: |
-            REPO_URL=${{ github.server_url }}/${{ github.repository }}.git
             RUST_TOOLCHAIN=${{ env.RUST_TOOLCHAIN }}
+            NETWORK=${{ matrix.network }}
+            MAINNET_BRANCH=${{ matrix.mainnet_branch }}
+            WASM_NAME=${{ matrix.wasm_name }}
             POLKADOT_BUILD_BRANCH=${{ matrix.relay_branch }}
             POLKADOT_LAUNCH_BRANCH=${{ env.POLKADOT_LAUNCH_BRANCH }}
-            # POLKADOT_MAINNET_BRANCH=${{ env.POLKADOT_MAINNET_BRANCH }}
-            # MAINNET_TAG=${{ matrix.mainnet_tag }}
-            MAINNET_BRANCH=${{ matrix.mainnet_branch }}
-            NETWORK=${{ matrix.network }}
-            # BRANCH=${{ github.head_ref }}
-            WASM_NAME=${{ matrix.wasm_name }}
 
-      - name: Show build configuration
-        run: cat .docker/docker-compose.${{ matrix.network }}.yml
+      - name: Show build Dockerfile
+        run: cat .docker/Dockerfile-parachain-upgrade.${{ matrix.network }}.yml
 
       - name: Generate launch-config-forkless-nodata.json
         uses: cuchi/jinja2-action@v1.2.0
         with:
           template: .docker/forkless-config/launch-config-forkless-nodata.j2
-          output_file: .docker/launch-config-forkless-nodata.json
+          output_file: .docker/forkless-config/launch-config-forkless-nodata.json
           variables: |
-            NETWORK=${{ matrix.network }}
             WASM_NAME=${{ matrix.wasm_name }}
             RELAY_CHAIN_TYPE=${{ env.RELAY_CHAIN_TYPE }}
 
       - name: Show launch-config-forkless configuration
-        run: cat .docker/launch-config-forkless-nodata.json
+        run: cat .docker/forkless-config/launch-config-forkless-nodata.json
+
+      - name: Run find-and-replace to remove slashes from branch name
+        uses: mad9000/actions-find-and-replace-string@3
+        id: branchname
+        with:
+          source: ${{ github.head_ref }}
+          find: '/'
+          replace: '-'
+
+      - name: Set build SHA
+        shell: bash
+        run: |
+          echo "BUILD_SHA=${LAST_COMMIT_SHA:0:8}" >> $GITHUB_ENV
+
+      - name: Build the stack
+        run: cd .docker/ && docker build --no-cache --file ./Dockerfile-parachain-upgrade.${{ matrix.network }}.yml --tag uniquenetwork/ci-forkless-nodata-local:${{ matrix.network }}-${{ steps.branchname.outputs.value }}-$BUILD_SHA .
+
+      - name: Push docker image version
+        run: docker push uniquenetwork/ci-forkless-nodata-local:${{ matrix.network }}-${{ steps.branchname.outputs.value }}-$BUILD_SHA
+
+      - name: Remove builder cache
+        if: always()                   # run this step always
+        run: |
+          docker builder prune -f
+          docker system prune -f
+
+
+  forkless-nodata-tests:
+    needs: [prepare-execution-marix, forkless-nodata-build]
+    # The type of runner that the job will run on
+    runs-on: [self-hosted-ci, large]
+
+    timeout-minutes: 600
+
+    name: ${{ matrix.network }}-nodata-tests
+
+    continue-on-error: false         #Do not stop testing of matrix runs failed.  As it decided during PR review - it required 50/50& Let's check it with false.
+
+    strategy:
+      matrix:
+        include: ${{fromJson(needs.prepare-execution-marix.outputs.matrix)}}
+
+    steps:
+      - name: Skip if pull request is in Draft
+        if: github.event.pull_request.draft == true
+        run: exit 1
+
+      - name: Clean Workspace
+        uses: AutoModality/action-clean@v1.1.0
+
+      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      - uses: actions/checkout@v3.1.0
+        with:
+          ref: ${{ github.head_ref }}  #Checking out head commit
+
+      - name: Prepare
+        uses: ./.github/actions/prepare
+
+      - name: Set build SHA
+        shell: bash
+        run: |
+          echo "BUILD_SHA=${LAST_COMMIT_SHA:0:8}" >> $GITHUB_ENV
+
+      - name: Run find-and-replace to remove slashes from branch name
+        uses: mad9000/actions-find-and-replace-string@2
+        id: branchname
+        with:
+          source: ${{ github.head_ref }}
+          find: '/'
+          replace: '-'
+
+      - name: Read .env file
+        uses: xom9ikk/dotenv@v2
+
+      - name: Generate ENV related extend file for docker-compose
+        uses: cuchi/jinja2-action@v1.2.0
+        with:
+          template: .docker/docker-compose.forkless-nodata.j2
+          output_file: .docker/docker-compose.forkless-nodata.${{ matrix.network }}.yml
+          variables: |
+            NETWORK=${{ matrix.network }}
+            BUILD_TAG=${{ steps.branchname.outputs.value }}-$BUILD_SHA
+
+      - name: Show build configuration
+        run: cat .docker/docker-compose.forkless-nodata.${{ matrix.network }}.yml
+
+      - name: Log in to Docker Hub
+        uses: docker/login-action@v2.0.0
+        with:
+          username: ${{ secrets.CORE_DOCKERHUB_USERNAME }}
+          password: ${{ secrets.CORE_DOCKERHUB_TOKEN }}
+
+      - name: Build the stack
+        run: docker-compose -f ".docker/docker-compose.forkless-nodata.${{ matrix.network }}.yml" up -d --remove-orphans --force-recreate --timeout 300
 
       - uses: actions/setup-node@v3.5.1
         with:
           node-version: 16
-
-      - name: Build the stack
-        run: docker-compose -f ".docker/docker-compose.${{ matrix.network }}.yml" up -d --build  --force-recreate --timeout 300
 
       - name: Check if docker logs consist logs related to Runtime Upgrade testing.
         if: success()
         run: |
           counter=160
           function check_container_status {
-                docker inspect -f {{.State.Running}} node-parachain
+                docker inspect -f {{.State.Running}} forkless-nodata
           }
           function do_docker_logs {
-                docker logs --details node-parachain  2>&1
+                docker logs --details forkless-nodata  2>&1
           }
           function is_started {
                 if [ "$(check_container_status)" == "true" ]; then
-                        echo "Container: node-parachain RUNNING";
+                        echo "Container: forkless-nodata RUNNING";
                         echo "Check Docker logs"
                         DOCKER_LOGS=$(do_docker_logs)
                         if [[ ${DOCKER_LOGS} = *"🛸 PARACHAINS' RUNTIME UPGRADE TESTING COMPLETE 🛸"* ]];then
@@ -133,7 +230,7 @@ jobs:
                                 return 1
                         fi
                 else
-                        echo "Container node-parachain not RUNNING"
+                        echo "Container forkless-nodata not RUNNING"
                         echo "Halting all future checks"
                         exit 1
                 fi
@@ -158,12 +255,12 @@ jobs:
         if: success() || failure()
         uses: jwalton/gh-docker-logs@v2.2.1
         with:
-          dest: './forkless-parachain-upgrade-nodata-logs.${{ matrix.features }}'
-          images: 'node-parachain'
+          dest: './forkless-parachain-upgrade-nodata-logs.${{ matrix.network }}'
+          images: 'forkless-nodata'
 
       - name: Show docker logs
         if: success() || failure()
-        run: cat './forkless-parachain-upgrade-nodata-logs.${{ matrix.features }}/node-parachain.log'
+        run: cat './forkless-parachain-upgrade-nodata-logs.${{ matrix.network }}/forkless-nodata.log'
 
       - name: Run Parallel tests
         working-directory: tests
@@ -212,7 +309,7 @@ jobs:
 
       - name: Stop running containers
         if: always()                   # run this step always
-        run: docker-compose -f ".docker/docker-compose.${{ matrix.network }}.yml" down
+        run: docker-compose -f ".docker/docker-compose.forkless-nodata.${{ matrix.network }}.yml" down
 
       - name: Remove builder cache
         if: always()                   # run this step always
