TMP disabled for debug for bash script.

diff --git a/.github/workflows/forkless-update-nodata.yml b/.github/workflows/forkless-update-nodata.yml
--- a/.github/workflows/forkless-update-nodata.yml
+++ b/.github/workflows/forkless-update-nodata.yml
@@ -112,9 +112,9 @@ jobs:
       - name: Build the stack
         run: docker-compose -f ".docker/docker-compose-forkless.yaml" -f ".docker/docker-compose.${{ matrix.network }}.yml" up -d --build  --force-recreate --timeout 300
 
-      - name: Wait for 5m before starting tests docker logs for " RUNTIME UPGRADE TESTING " criteria
-        if: success()
-        run: sleep 300s
+#      - name: Wait for 5m before starting tests docker logs for " RUNTIME UPGRADE TESTING " criteria
+#        if: success()
+#        run: sleep 300s
 
       - name: Check if docker logs consist logs related to Runtime Upgrade testing.
         if: success()
@@ -123,13 +123,13 @@ jobs:
                  DOCKER_LOGS=$(docker logs --details node-parachain  2>&1)
             }
             function is_started {
-                 if [[ ${DOCKER_LOGS} != *"PARACHAINS' RUNTIME UPGRADE TESTING"* ]];then
+                 if [[ ${DOCKER_LOGS} != *"RUNTIME UPGRADE TESTING"* ]];then
                     return 0
                  fi
                     return 1
             }
             while ! is_started; do
-                 echo "Waiting for "PARACHAINS' RUNTIME UPGRADE TESTING" in container logs"
+                 echo "Waiting for "RUNTIME UPGRADE TESTING" in container logs"
                  sleep 15s
             done
             echo "Test completed."
@@ -137,23 +137,23 @@ jobs:
         shell: bash
 
 
-      - name: Collect Docker Logs
-        if: success() || failure()
-        uses: jwalton/gh-docker-logs@v2.2.0
-        with:
-          dest: './forkless-parachain-upgrade-nodata-logs.${{ matrix.features }}'
-          images: 'node-parachain' 
-
-      - name: Tar logs
-        if: success() || failure()
-        run: tar cvzf ./forkless-parachain-upgrade-nodata-logs.${{ matrix.features }}.tgz ./forkless-parachain-upgrade-nodata-logs.${{ matrix.features }}
-
-      - name: Upload logs to GitHub
-        if: success() || failure()
-        uses: actions/upload-artifact@master
-        with:
-          name: forkless-parachain-upgrade-nodata-logs.${{ matrix.features }}.tgz
-          path: ./forkless-parachain-upgrade-nodata-logs.${{ matrix.features }}.tgz
+#      - name: Collect Docker Logs
+#        if: success() || failure()
+#        uses: jwalton/gh-docker-logs@v2.2.0
+#        with:
+#          dest: './forkless-parachain-upgrade-nodata-logs.${{ matrix.features }}'
+#          images: 'node-parachain' 
+#
+#      - name: Tar logs
+#        if: success() || failure()
+#        run: tar cvzf ./forkless-parachain-upgrade-nodata-logs.${{ matrix.features }}.tgz ./forkless-parachain-upgrade-nodata-logs.${{ matrix.features }}
+#
+#      - name: Upload logs to GitHub
+#        if: success() || failure()
+#        uses: actions/upload-artifact@master
+#        with:
+#          name: forkless-parachain-upgrade-nodata-logs.${{ matrix.features }}.tgz
+#          path: ./forkless-parachain-upgrade-nodata-logs.${{ matrix.features }}.tgz
 
 
 #      - name: Test Report
@@ -170,6 +170,6 @@ jobs:
 #          echo "url is ${{ steps.test-report.outputs.runHtmlUrl }}"
 
 
-      - name: Stop running containers
-        if: always()                   # run this step always
-        run: docker-compose -f ".docker/docker-compose-forkless.yaml" -f ".docker/docker-compose.${{ matrix.network }}.yml" down
+#      - name: Stop running containers
+#        if: always()                   # run this step always
+#        run: docker-compose -f ".docker/docker-compose-forkless.yaml" -f ".docker/docker-compose.${{ matrix.network }}.yml" down
