Debug: step by step.

diff --git a/.github/workflows/market-test_v2.yml b/.github/workflows/market-test_v2.yml
--- a/.github/workflows/market-test_v2.yml
+++ b/.github/workflows/market-test_v2.yml
@@ -22,10 +22,10 @@ jobs:
         include:
           - network: "opal"
             features: "opal-runtime"
-          - network: "quartz"
-            features: "quartz-runtime"
-          - network: "unique"
-            features: "unique-runtime"
+#          - network: "quartz"
+#            features: "quartz-runtime"
+#          - network: "unique"
+#            features: "unique-runtime"
 
     steps:
 
@@ -48,21 +48,21 @@ jobs:
 #          ref: 'CI-37-core-ci-step-3'
           ref: 'ci_test_v2'
 
-      - name: Read .env file
-        uses: xom9ikk/dotenv@v1.0.2
+#      - name: Read .env file
+#        uses: xom9ikk/dotenv@v1.0.2
       
       - name: Copy qa-tests/.env.example to qa-tests/.env
         working-directory: qa-tests
         run: cp .env.docker .env
 
-      - name: Show content of qa-test/.env
-        working-directory: qa-tests
-        run: cat .env
-
-      - name: Read qa -test .env file
-        uses: xom9ikk/dotenv@v1.0.2
-        with:
-          path: qa-tests/
+#      - name: Show content of qa-test/.env
+#        working-directory: qa-tests
+#        run: cat .env
+#
+#      - name: Read qa -test .env file
+#        uses: xom9ikk/dotenv@v1.0.2
+#        with:
+#          path: qa-tests/
         
       - name: Generate ENV related extend file for docker-compose
         uses: cuchi/jinja2-action@v1.2.0
@@ -85,36 +85,36 @@ jobs:
         working-directory: qa-tests
         run: docker-compose -f ".docker/docker-compose.market.yml" -f ".docker/docker-compose.${{ matrix.network }}.yml" up -d --build --remove-orphans --force-recreate node-parachain 
 
-      - name: Start nonce-app
-        working-directory: qa-tests
-        run: docker-compose -f ".docker/docker-compose.market.yml" up -d --build --remove-orphans --force-recreate nonce-app 
+#      - name: Start nonce-app
+#        working-directory: qa-tests
+#        run: docker-compose -f ".docker/docker-compose.market.yml" up -d --build --remove-orphans --force-recreate nonce-app 
      
       - uses: actions/setup-node@v3
         with:
-          node-version: 16
+          node-version: 16.17
 
       - name: Setup TypeScript
         working-directory: qa-tests
         run: |
-          npm install
           npm install -g ts-node
+          npm install
 
-      - name: Copy qa-tests/.env.example to qa-tests/.env
+      - name: Copy qa-tests/.env.docker to qa-tests/.env
         working-directory: qa-tests
         run: | 
           rm -rf .env
-          cp .env.example .env
+          cp .env.docker .env
       
      
-      - name: Show content of qa-test/.env
-        working-directory: qa-tests
-        run: cat .env
+#      - name: Show content of qa-test/.env
+#        working-directory: qa-tests
+#        run: cat .env
 
 
-      - name: Read qa -test .env file
-        uses: xom9ikk/dotenv@v1.0.2
-        with:
-          path: qa-tests/
+#      - name: Read qa -test .env file
+#        uses: xom9ikk/dotenv@v1.0.2
+#        with:
+#          path: qa-tests/
 
       - name: Wait for chain up and running
         working-directory: tests
@@ -127,9 +127,9 @@ jobs:
         working-directory: qa-tests
         run: |
           cat .env
-          cat .env.example 
-          cat .env.docker
-          cat .env.example.ci
+#          cat .env.example 
+#          cat .env.docker
+#          cat .env.example.ci
           ts-node ./src/scripts/create-market-accounts.ts
 
       - name: Get chain logs
@@ -151,56 +151,56 @@ jobs:
         if: failure()
         run: sleep 900s
 
-      - name: Import test data
-        working-directory: qa-tests
-        run: ts-node ./src/scripts/create-test-collections.ts
+#      - name: Import test data
+#        working-directory: qa-tests
+#        run: ts-node ./src/scripts/create-test-collections.ts
 
-      - name: Show content of qa-test .env
-        working-directory: qa-tests
-        run: cat .env
+#      - name: Show content of qa-test .env
+#        working-directory: qa-tests
+#        run: cat .env
 
-      - name: Copy qa-tests/.env.example to qa-tests/.env.docker
-        working-directory: qa-tests
-        run: |
-          rm -rf .env.docker
-          cp .env .env.docker
-          sed -i '/UNIQUE_WS_ENDPOINT/c UNIQUE_WS_ENDPOINT=ws://node-parachain:9944' .env.docker
+#      - name: Copy qa-tests/.env.example to qa-tests/.env.docker
+#        working-directory: qa-tests
+#        run: |
+#          rm -rf .env.docker
+#          cp .env .env.docker
+#          sed -i '/UNIQUE_WS_ENDPOINT/c UNIQUE_WS_ENDPOINT=ws://node-parachain:9944' .env.docker
 
-      - name: Read qa -test .env file Before market start
-        uses: xom9ikk/dotenv@v1.0.2
-        with:
-          path: qa-tests/
+#      - name: Read qa -test .env file Before market start
+#        uses: xom9ikk/dotenv@v1.0.2
+#        with:
+#          path: qa-tests/
 
-      - name: local-market:start
-        run: docker-compose -f "qa-tests/.docker/docker-compose.market.yml" -f "qa-tests/.docker/docker-compose.${{ matrix.network }}.yml" up -d --build
+#      - name: local-market:start
+#        run: docker-compose -f "qa-tests/.docker/docker-compose.market.yml" -f "qa-tests/.docker/docker-compose.${{ matrix.network }}.yml" up -d --build
 
-      - name: Wait for market readyness
-        working-directory: qa-tests
-        run: src/scripts/wait-market-ready.sh
-        shell: bash
+#      - name: Wait for market readyness
+#        working-directory: qa-tests
+#        run: src/scripts/wait-market-ready.sh
+#        shell: bash
 
-      - name: Install dependecies
-        working-directory: qa-tests
-        run: |
-          npm ci
-          npm install -D @playwright/test
-          npx playwright install-deps
-          npx playwright install
+#      - name: Install dependecies
+#        working-directory: qa-tests
+#        run: |
+#          npm ci
+#          npm install -D @playwright/test
+#          npx playwright install-deps
+#          npx playwright install
           
-      - name: 
-        working-directory: qa-tests
-        run: |
-          npx playwright test --workers=8 --quiet .*.api.test.ts --reporter=github --config playwright.config.ts
+#      - name: 
+#        working-directory: qa-tests
+#        run: |
+#          npx playwright test --workers=8 --quiet .*.api.test.ts --reporter=github --config playwright.config.ts
 
-      - name: Show env variables
-        if: success() || failure()
-        run: printenv
+#      - name: Show env variables
+#        if: success() || failure()
+#        run: printenv
 
-      - name: look up for report
-        if: success() || failure()
-        run: |
-          ls -la 
-          ls -la qa-tests/
+#      - name: look up for report
+#        if: success() || failure()
+#        run: |
+#          ls -la 
+#          ls -la qa-tests/
 
 
       - name: Stop running containers
