re-enabled steps in workflow.

diff --git a/.github/workflows/node_build_test.yml b/.github/workflows/node_build_test.yml
--- a/.github/workflows/node_build_test.yml
+++ b/.github/workflows/node_build_test.yml
@@ -82,8 +82,8 @@ jobs:
       - name: Build the stack
         run: docker-compose -f ".docker/docker-compose-dev.yaml" -f ".docker/docker-compose.${{ matrix.network }}.yml" up -d --build
 
-    #  - name: Wait
-    #    run: sleep 420s
+      - name: Wait
+        run: sleep 420s
 
       - name: Install node
         uses: actions/setup-node@v1
@@ -99,22 +99,21 @@ jobs:
 
       - name: Run tests
         run: |
-          chmod u+x .docker/readyness.js &&  .docker/readyness.js
           cd tests
           NOW=$(date +%s) && yarn test --reporter mochawesome --reporter-options reportFilename=test-${NOW}
         env:
           RPC_URL: http://127.0.0.1:9933/
 
-#      - name: Test Report
-#        uses: phoenix-actions/test-reporting@v8
-#        id: test-report               # Set ID reference for step
-#        if: success() || failure()    # run this step even if previous step failed
-#        with:
-#          name: Tests ${{ matrix.network }}            # Name of the check run which will be created
-#          path: tests/mochawesome-report/test-*.json    # Path to test results
-#          reporter: mochawesome-json
-#          fail-on-error: 'false'
+      - name: Test Report
+        uses: phoenix-actions/test-reporting@v8
+        id: test-report               # Set ID reference for step
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Tests ${{ matrix.network }}            # Name of the check run which will be created
+          path: tests/mochawesome-report/test-*.json    # Path to test results
+          reporter: mochawesome-json
+          fail-on-error: 'false'
 
-#      - name: Stop running containers
-#        if: always()                   # run this step always
-#        run: docker-compose -f ".docker/docker-compose-dev.yaml" -f ".docker/docker-compose.${{ matrix.network }}.yml" down
+      - name: Stop running containers
+        if: always()                   # run this step always
+        run: docker-compose -f ".docker/docker-compose-dev.yaml" -f ".docker/docker-compose.${{ matrix.network }}.yml" down
