Update node-only-update_v2.yml

diff --git a/.github/workflows/node-only-update_v2.yml b/.github/workflows/node-only-update_v2.yml
--- a/.github/workflows/node-only-update_v2.yml
+++ b/.github/workflows/node-only-update_v2.yml
@@ -162,28 +162,49 @@ jobs:
           ref: ${{ matrix.mainnet_branch }}  #Checking out head commit
           path: ${{ matrix.mainnet_branch }}
 
-
-      # TODO change this step to use testParallel script after the merge
-      - name: Run Parallel tests before Node Parachain upgrade
+      - name: Run tests before Node Parachain upgrade
         working-directory: ${{ matrix.mainnet_branch }}/tests
         run: |
           yarn install
           yarn add mochawesome
           echo "Ready to start tests"
           yarn polkadot-types
-          NOW=$(date +%s) && yarn testParallel --reporter mochawesome --reporter-options reportFilename=test-parallel-${NOW}
+          NOW=$(date +%s) && yarn test --reporter mochawesome --reporter-options reportFilename=test-${NOW}
         env:
           RPC_URL: http://127.0.0.1:9933/
 
       - name: Upload Parallel Test Report Before Node upgrade
         uses: phoenix-actions/test-reporting@v8
-        id: test-parallel-report-before
+        id: test-report-before
         if: success() || failure()    # run this step even if previous step failed
         with:
           name: Tests before node upgrade ${{ matrix.network }}            # Name of the check run which will be created
-          path: ${{ matrix.mainnet_branch }}/tests/mochawesome-report/test-parallel-*.json    # Path to test results
+          path: ${{ matrix.mainnet_branch }}/tests/mochawesome-report/test-*.json    # Path to test results
           reporter: mochawesome-json
           fail-on-error: 'false'
+
+
+      ## TODO change this step to use testParallel script after the merge
+      #- name: Run Parallel tests before Node Parachain upgrade
+      #  working-directory: ${{ matrix.mainnet_branch }}/tests
+      #  run: |
+      #    yarn install
+      #    yarn add mochawesome
+      #    echo "Ready to start tests"
+      #    yarn polkadot-types
+      #    NOW=$(date +%s) && yarn testParallel --reporter mochawesome --reporter-options reportFilename=test-parallel-${NOW}
+      #  env:
+      #    RPC_URL: http://127.0.0.1:9933/
+
+      #- name: Upload Parallel Test Report Before Node upgrade
+      #  uses: phoenix-actions/test-reporting@v8
+      #  id: test-parallel-report-before
+      #  if: success() || failure()    # run this step even if previous step failed
+      #  with:
+      #    name: Tests before node upgrade ${{ matrix.network }}            # Name of the check run which will be created
+      #    path: ${{ matrix.mainnet_branch }}/tests/mochawesome-report/test-parallel-*.json    # Path to test results
+      #    reporter: mochawesome-json
+      #    fail-on-error: 'false'
 
       # TODO uncomment thease steps after the merge
       # - name: Run Sequential tests before Node Parachain upgrade
@@ -270,8 +291,9 @@ jobs:
           echo "Halting script"
           exit 0
         shell: bash
-
-      - name: Run Parallel tests after Node Parachain upgrade
+        
+      ## TODO: Remove next two blocks before switch to Parrallel & Sequental tests. Uncoment commented blocks.
+      - name: Run tests after Node Parachain upgrade
         working-directory: ${{ matrix.mainnet_branch }}/tests
         run: |
           yarn install
@@ -279,36 +301,58 @@ jobs:
           node scripts/readyness.js
           echo "Ready to start tests"
           yarn polkadot-types
-          NOW=$(date +%s) && yarn testParallel --reporter mochawesome --reporter-options reportFilename=test-parallel-${NOW}
+          NOW=$(date +%s) && yarn test --reporter mochawesome --reporter-options reportFilename=test-${NOW}
         env:
           RPC_URL: http://127.0.0.1:9933/
 
-      - name: Test Report Parallel After Node upgrade
+      - name: Test Report After Node upgrade
         uses: phoenix-actions/test-reporting@v8
-        id: test-report-parallel-after
+        id: test-report-after
         if: success() || failure()    # run this step even if previous step failed
         with:
           name: Tests after node upgrade ${{ matrix.network }}            # Name of the check run which will be created
-          path: ${{ matrix.mainnet_branch }}/tests/mochawesome-report/test-parallel-*.json    # Path to test results
+          path: ${{ matrix.mainnet_branch }}/tests/mochawesome-report/test-*.json    # Path to test results
           reporter: mochawesome-json
           fail-on-error: 'false'
-      
-      - name: Run Sequential tests after Node Parachain upgrade
-        if: success() || failure()
-        working-directory: ${{ matrix.mainnet_branch }}/tests
-        run: NOW=$(date +%s) && yarn testSequential --reporter mochawesome --reporter-options reportFilename=test-sequential-${NOW}
-        env:
-          RPC_URL: http://127.0.0.1:9933/
 
-      - name: Upload Sequential Test Report After Node upgrade
-        uses: phoenix-actions/test-reporting@v8
-        id: test-sequential-report-after
-        if: success() || failure()    # run this step even if previous step failed
-        with:
-          name: Tests before node upgrade ${{ matrix.network }}            # Name of the check run which will be created
-          path: ${{ matrix.mainnet_branch }}/tests/mochawesome-report/test-sequential-*.json    # Path to test results
-          reporter: mochawesome-json
-          fail-on-error: 'false'
+      #- name: Run Parallel tests after Node Parachain upgrade
+      #  working-directory: ${{ matrix.mainnet_branch }}/tests
+      #  run: |
+      #    yarn install
+      #    yarn add mochawesome
+      #    node scripts/readyness.js
+      #    echo "Ready to start tests"
+      #    yarn polkadot-types
+      #    NOW=$(date +%s) && yarn testParallel --reporter mochawesome --reporter-options reportFilename=test-parallel-${NOW}
+      #  env:
+      #    RPC_URL: http://127.0.0.1:9933/
+
+      #- name: Test Report Parallel After Node upgrade
+      #  uses: phoenix-actions/test-reporting@v8
+      #  id: test-report-parallel-after
+      #  if: success() || failure()    # run this step even if previous step failed
+      #  with:
+      #    name: Tests after node upgrade ${{ matrix.network }}            # Name of the check run which will be created
+      #    path: ${{ matrix.mainnet_branch }}/tests/mochawesome-report/test-parallel-*.json    # Path to test results
+      #    reporter: mochawesome-json
+      #    fail-on-error: 'false'
+      
+      #- name: Run Sequential tests after Node Parachain upgrade
+      #  if: success() || failure()
+      #  working-directory: ${{ matrix.mainnet_branch }}/tests
+      #  run: NOW=$(date +%s) && yarn testSequential --reporter mochawesome --reporter-options reportFilename=test-sequential-${NOW}
+      #  env:
+      #    RPC_URL: http://127.0.0.1:9933/
+
+      #- name: Upload Sequential Test Report After Node upgrade
+      #  uses: phoenix-actions/test-reporting@v8
+      #  id: test-sequential-report-after
+      #  if: success() || failure()    # run this step even if previous step failed
+      #  with:
+      #    name: Tests before node upgrade ${{ matrix.network }}            # Name of the check run which will be created
+      #    path: ${{ matrix.mainnet_branch }}/tests/mochawesome-report/test-sequential-*.json    # Path to test results
+      #    reporter: mochawesome-json
+      #    fail-on-error: 'false'
 
 
       - name: Stop running containers
