Update node-only-update_v2.yml

diff --git a/.github/workflows/node-only-update_v2.yml b/.github/workflows/node-only-update_v2.yml
--- a/.github/workflows/node-only-update_v2.yml
+++ b/.github/workflows/node-only-update_v2.yml
@@ -163,24 +163,45 @@ jobs:
           path: ${{ matrix.mainnet_branch }}
 
 
-      - name: Run tests before Node Parachain upgrade
+      - name: Run Parallel tests before Node Parachain upgrade
         working-directory: ${{ matrix.mainnet_branch }}/tests
         run: |
           yarn install
           yarn add mochawesome
           echo "Ready to start tests"
           yarn polkadot-types
-          NOW=$(date +%s) && yarn testParallelFull --reporter mochawesome --reporter-options reportFilename=test-${NOW}
+          NOW=$(date +%s) && yarn testParallel --reporter mochawesome --reporter-options reportFilename=test-parallel-${NOW}
         env:
           RPC_URL: http://127.0.0.1:9933/
 
-      - name: Test Report Before Node upgrade
+      - name: Upload Parallel Test Report Before Node upgrade
         uses: phoenix-actions/test-reporting@v8
         id: test-report-before
         if: success() || failure()    # run this step even if previous step failed
         with:
           name: Tests before node upgrade ${{ matrix.network }}            # Name of the check run which will be created
-          path: ${{ matrix.mainnet_branch }}/tests/mochawesome-report/test-*.json    # Path to test results
+          path: ${{ matrix.mainnet_branch }}/tests/mochawesome-report/test-parallel-*.json    # Path to test results
+          reporter: mochawesome-json
+          fail-on-error: 'false'
+
+      - name: Run Parallel tests before Node Parachain upgrade
+        working-directory: ${{ matrix.mainnet_branch }}/tests
+        run: |
+          yarn install
+          yarn add mochawesome
+          echo "Ready to start tests"
+          yarn polkadot-types
+          NOW=$(date +%s) && yarn testSequential --reporter mochawesome --reporter-options reportFilename=test-sequential-${NOW}
+        env:
+          RPC_URL: http://127.0.0.1:9933/
+
+      - name: Upload Sequential Test Report Before Node upgrade
+        uses: phoenix-actions/test-reporting@v8
+        id: test-report-before
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Tests before node upgrade ${{ matrix.network }}            # Name of the check run which will be created
+          path: ${{ matrix.mainnet_branch }}/tests/mochawesome-report/test-sequential-*.json    # Path to test results
           reporter: mochawesome-json
           fail-on-error: 'false'
 
