set timeout for logs and disable second logs report

diff --git a/.github/workflows/node-only-update_v2.yml b/.github/workflows/node-only-update_v2.yml
--- a/.github/workflows/node-only-update_v2.yml
+++ b/.github/workflows/node-only-update_v2.yml
@@ -230,12 +230,12 @@ jobs:
           ContainerID=$(docker ps -aqf "name=node-parachain")
           PID=$(docker exec node-parachain pidof 'polkadot-launch')
           sleep 30s
-          echo -e "Show logs of node-parachain container.\n"
-          docker logs ${ContainerID}
           echo -e "\n"
           echo -e "Restart polkadot-launch process: $PID\n"
           docker exec node-parachain kill -SIGUSR1 ${PID}
           echo "SIGUSR1 sent to Polkadot-launch PID: $PID"
+          sleep 60s
+          echo -e "Show logs of node-parachain container.\n"          
           docker logs ${ContainerID}
       
       - name: Tail chain logs in case of docker image crashed after Polkadot Launch restart
@@ -320,16 +320,16 @@ jobs:
         env:
           RPC_URL: http://127.0.0.1:9933/
 
-      - name: Test Report After Node upgrade
-        uses: phoenix-actions/test-reporting@v8
-        id: test-report-after
-        if: success() || failure()    # run this step even if previous step failed
-        with:
-          name: Tests after node upgrade ${{ matrix.network }}            # Name of the check run which will be created
-          path: ${{ matrix.mainnet_branch }}/tests/mochawesome-report/test-after-*.json    # Path to test results
-          reporter: mochawesome-json
-          fail-on-error: 'false'
-          token: ${{ secrets.GITHUB_TOKEN }}
+      # - name: Test Report After Node upgrade
+      #   uses: phoenix-actions/test-reporting@v8
+      #   id: test-report-after
+      #   if: success() || failure()    # run this step even if previous step failed
+      #   with:
+      #     name: Tests after node upgrade ${{ matrix.network }}            # Name of the check run which will be created
+      #     path: ${{ matrix.mainnet_branch }}/tests/mochawesome-report/test-after-*.json    # Path to test results
+      #     reporter: mochawesome-json
+      #     fail-on-error: 'false'
+      #     token: ${{ secrets.GITHUB_TOKEN }}
 
       # TODO uncomment thease steps after the merge
       #- name: Run Parallel tests after Node Parachain upgrade
