Update node-only-update_v2.yml

diff --git a/.github/workflows/node-only-update_v2.yml b/.github/workflows/node-only-update_v2.yml
--- a/.github/workflows/node-only-update_v2.yml
+++ b/.github/workflows/node-only-update_v2.yml
@@ -184,14 +184,10 @@ jobs:
           reporter: mochawesome-json
           fail-on-error: 'false'
 
-      - name: Run Parallel tests before Node Parachain upgrade
+      - name: Run Sequential tests before Node Parachain upgrade
+        if: success() || failure()
         working-directory: ${{ matrix.mainnet_branch }}/tests
-        run: |
-          yarn install
-          yarn add mochawesome
-          echo "Ready to start tests"
-          yarn polkadot-types
-          NOW=$(date +%s) && yarn testSequential --reporter mochawesome --reporter-options reportFilename=test-sequential-${NOW}
+        run: NOW=$(date +%s) && yarn testSequential --reporter mochawesome --reporter-options reportFilename=test-sequential-${NOW}
         env:
           RPC_URL: http://127.0.0.1:9933/
 
@@ -262,23 +258,34 @@ jobs:
 
       - name: Run tests after Node Parachain upgrade
         working-directory: tests
-        run: |
-          yarn install
-          yarn add mochawesome
-          node scripts/readyness.js
-          echo "Ready to start tests"
-          yarn polkadot-types
-          NOW=$(date +%s) && yarn testParallelFull --reporter mochawesome --reporter-options reportFilename=test-${NOW}
+        run: NOW=$(date +%s) && yarn testParallel --reporter mochawesome --reporter-options reportFilename=test-parallel-${NOW}
         env:
           RPC_URL: http://127.0.0.1:9933/
 
-      - name: Test Report After Node upgrade
+      - name: Test Report Parallel After Node upgrade
         uses: phoenix-actions/test-reporting@v8
-        id: test-report-after
+        id: test-report-parallel-after
         if: success() || failure()    # run this step even if previous step failed
         with:
           name: Tests after node upgrade ${{ matrix.network }}            # Name of the check run which will be created
-          path: tests/mochawesome-report/test-*.json    # Path to test results
+          path: tests/mochawesome-report/test-parallel-*.json    # Path to test results
+          reporter: mochawesome-json
+          fail-on-error: 'false'
+      
+      - name: Run Sequential tests before Node Parachain upgrade
+        if: success() || failure()
+        working-directory: ${{ matrix.mainnet_branch }}/tests
+        run: NOW=$(date +%s) && yarn testSequential --reporter mochawesome --reporter-options reportFilename=test-sequential-${NOW}
+        env:
+          RPC_URL: http://127.0.0.1:9933/
+
+      - name: Upload Sequential Test Report After Node upgrade
+        uses: phoenix-actions/test-reporting@v8
+        id: test-sequential-report-after
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Tests before node upgrade ${{ matrix.network }}            # Name of the check run which will be created
+          path: ${{ matrix.mainnet_branch }}/tests/mochawesome-report/test-sequential-*.json    # Path to test results
           reporter: mochawesome-json
           fail-on-error: 'false'
 
