Ci build workflow (#39)
* Temporary remove actions from workflow directory.
Added listing for target directory.

* dded listing for src sub-dirs

* Added yet another listing for directory.

* Path fix

* Added test to actions.

* typo fixd

* Added build and directory listing

* Try four.

* Added pre-requisites job.

* Added installation of subwasm into pre-requisites.

* Added steps to recreate release dir.

* env variableds moved to upper string

* One build task has been splited for several for each chain net

* Fix: Added reference for workflow variables

* Added extra spaces

* Changed path to working directory.

* Changed path in varibales.

* Added test steps as dependencie for build Opal.

* Removed Workspace cleanup

* Remove not existing option from build string

* Switching to tests.

* Repo fix.

* Build and run

* docker compose file name changed.

* Added shuting down step

* Adding additional step for lunching tests

* Try 5

* Added spacing before step.

* Added cd to tests path

* Added port mapping

* Added expose ports

* cking

* Added dockerfile-parachain-v2

* Try 6

* Fixing state

* Get rid off wait script

* dded mocha installation

* Changed test

diff --git a/.github/workflows/node_build_test.yml b/.github/workflows/node_build_test.yml
--- a/.github/workflows/node_build_test.yml
+++ b/.github/workflows/node_build_test.yml
@@ -92,9 +92,17 @@ jobs:
       - name: Run tests
         run: |
           cd tests
-          NOW=$(date +%s) && yarn testNesting --reporter mochawesome --reporter-options reportFilename=test-${NOW}
-          ls -la
+          NOW=$(date +%s) && yarn testConnection --reporter mochawesome --reporter-options reportFilename=test-${NOW}
 
+      - name: Test Report
+        uses: phoenix-actions/test-reporting@v8
+        id: test-report               # Set ID reference for step
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Tests            # Name of the check run which will be created
+          path: tests/mochawesome-report/test-*.json    # Path to test results
+          reporter: mochawesome-json
+          
       - name: Stop containers
         if: always()
         run: docker-compose -f "docker-compose-tests-parachain.yml" down
