xcm testnet workflow

diff --git a/.github/workflows/xcm-testnet.yml b/.github/workflows/xcm-testnet.yml
--- a/.github/workflows/xcm-testnet.yml
+++ b/.github/workflows/xcm-testnet.yml
@@ -128,16 +128,16 @@ jobs:
       - name: Build the stack
         run: cd .docker/ && docker build --file ./Dockerfile-xcm.${{ matrix.network }}.yml --tag xcm-nodes-${{ matrix.network }} --tag uniquenetwork/xcm-${{ matrix.network }}-testnet-local:nightly-${{ github.head_ref }}-${{ github.sha }} --tag uniquenetwork/xcm-${{ matrix.network }}-testnet-local:latest .
 
-      - name: Collect Docker Logs
-        if: success() || failure()
-        uses: jwalton/gh-docker-logs@v2.2.0
-        with:
-          dest: './xcm-build-logs.${{ matrix.features }}'
-          images: 'xcm-nodes-${{ matrix.network }}'
+          #      - name: Collect Docker Logs
+          #        if: success() || failure()
+          #        uses: jwalton/gh-docker-logs@v2.2.0
+          #        with:
+          #          dest: './xcm-build-logs.${{ matrix.features }}'
+          #          images: 'xcm-nodes-${{ matrix.network }}'
 
-      - name: Show docker logs
-        if: success() || failure()
-        run: cat './xcm-build-logs.${{ matrix.features }}/xcm-nodes-${{ matrix.network }}.log'
+          #      - name: Show docker logs
+          #        if: success() || failure()
+          #        run: cat './xcm-build-logs.${{ matrix.features }}/xcm-nodes-${{ matrix.network }}.log'
 
       - name: Log in to Docker Hub
         uses: docker/login-action@v2.0.0
